### ISSUE TITLE
Performance issues.

### ISSUE THREAD

**Issue by davidnknight** [juanfran/gulp-scss-lint#12]
Hi!

I'm seeing serious performance issues running SCSSlint on one of three stylesheets. The stylesheet in question does have quite a few @include's but not hundreds, and the whole point of SCSS is to be more modular, so I'm reluctant to start removing some of those and combining them.

Anyway, with scsslint, compile time is 6+ seconds, without it's ~900ms. There are also no errors, I've fixed what scsslint pulled up.

That said, two other stylesheets don't really seem affected but they're single files with no @includes.

Any ideas?

**Comment by erwinw** [comment]
Perhaps you could checksum files and only lint the ones that have changed or had errors?

**Comment by replete** [comment]
6s to 900ms reflects my experiences moving from Ruby sass to libsass. 

I would imagine it's because Ruby is parsing the sass, which is slower than libsass which is written in C to be performant.
