### ISSUE TITLE
Plugin fails if there are spaces in the directory name

### ISSUE THREAD

**Issue by bmds** [juanfran/gulp-scss-lint#18]
If the directory your gulpfile resides in contains spaces in it's name then gulp-scss-lint fails to find index.js to run, outputting the following error:

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error in plugin '←[36mgulp-scss-lint←[39m'
Input file did not exist or was not readable
    at D:\Projects\project with spaces\node_modules\gulp-scss-lint\src\index.js:63:32
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

If the directory is renamed to remove the spaces then gulp-scss-lint works. This is the only package that fails, all of the others resolve correctly.

I only had time to test this on Window 7, i'll run a test on OSX on Monday if needed.

**Comment by juanfran** [comment]
thanks @bmds !!

I try in differents OS and only fail in windows. I fix it it in the last release, thanks
