### ISSUE TITLE
Replace execSync with exec-sync?

### ISSUE THREAD

**Issue by alexweber** [juanfran/gulp-scss-lint#25]
[execSync](https://github.com/mgutz/execSync) is no longer supported.  Apparently `execSync()` exists in both io.js and node 0.12 but it might be best to switch it out for the [exec-sync](https://www.npmjs.com/package/exec-sync) package?

**Comment by juanfran** [comment]
thanks @alexweber 

`gulp-scss-lint` uses the node native execSync if it can.

I will replace execSync by [sync-exec](https://www.npmjs.com/package/sync-exec) for older versions of Node, [exec-sync](https://github.com/jeremyfa/node-exec-sync) is also not maintained.

**Comment by jdhartley** [comment]
Any updates on this? execSync is throwing a fit trying to compile some native extensions

**Comment by juanfran** [comment]
sorry I had forgotten :disappointed:

**Comment by juanfran** [comment]
merged https://github.com/juanfran/gulp-scss-lint/pull/29 thanks!!

**Comment by jdhartley** [comment]
Awesome, thanks @juanfran! Do we need a version bump to have these changes take effect?

**Comment by alexweber** [comment]
Sweet, thanks @jdhartley & @juanfran!

**Comment by juanfran** [comment]
I've committed the version 0.1.12 with this change

**Comment by jdhartley** [comment]
Thanks man! :tada:
