### ISSUE TITLE
failReporter exits 1 on warning

### ISSUE THREAD

**Issue by mlarcher** [juanfran/gulp-scss-lint#28]
It seems the failReporter will exit 1 on errors, but also on warnings. Is it intentionnal ? I would expect a softer exit for warnings.
I might be wrong, but it seems to me that it would just be a matter of changing
```
if (!file.scsslint.success) {
```
to
```
if (file.scsslint.errors > 0) {
```
in reporter.js

**Comment by juanfran** [comment]
thanks for your feedback

I've added a parameter to failReporter

```js
.pipe(scsslint.failReporter('E'))
```
with an 'E' gulp-scss-lint only fails with errors

**Comment by mlarcher** [comment]
@juanfran any idea when the next release will make it available ?

**Comment by juanfran** [comment]
right now :smile:
