### ISSUE TITLE
gulp-scss-lint fails for scss_lint v.0.39.0

### ISSUE THREAD

**Issue by alansouzati** [juanfran/gulp-scss-lint#34]
Hi,

  I've just updated my gem scss_lint to version 0.39.0 and after this update I can run `gulp-scss-lint` anymore. It seems to be something related to the command-line arguments. 

```
{ [Error: Command line usage error]
  message: 'Command line usage error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-scss-lint',
  __safety: { toString: [Function] } }
```

If I revert my scss_lint to version 0.38.0 everything works as expected.

I'm an OSX user and my Node version is 0.12 and Npm version is 2.7.5.

Any help appreciated.

Alan

**Comment by juanfran** [comment]
are you using gulp-scss-lint 0.2.0?

**Comment by alansouzati** [comment]
I thought that it was. I have my package.json as `gulp-scss-lint": "^0.1.10`, I was expecting it to match 0.x.x. I guess my understanding about caret was wrong.

Updating to 0.2.0 works! Thanks

**Comment by brunowego** [comment]
See also https://github.com/juanfran/gulp-scss-lint/issues/34
