### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by adam-l** [juanfran/gulp-scss-lint#37]
I am trying to run gulp-scss-lint, but all I get is this:
[02:13:50] Starting 'scss-lint'...
[02:13:50] 'scss-lint' errored after 33 ms
[02:13:50] Error in plugin 'gulp-scss-lint'
Message:
    Error code ENOENT
Error: spawn ENOENT

When I run 'ruby -v' I get:
ruby 2.0.0p247 (2013-06-27) [i386-mingw32]

I have scss-lint installed. I am using Windows 8. Can anyone help?

**Comment by juanfran** [comment]
Are you using the latest version of [scss-lint](https://github.com/brigade/scss-lint)?

**Comment by adam-l** [comment]
https://github.com/brigade/scss-lint says that the latest one is 0.39.0. The latest one that I could install however was 0.38.0

C:\WINDOWS\system32>gem uninstall scss-lint
Remove executables:
        scss-lint

in addition to the gem? [Yn]  y
Removing scss-lint
Successfully uninstalled scss-lint-0.38.0

C:\WINDOWS\system32>gem install scss-lint -v 0.39.0
ERROR:  Could not find a valid gem 'scss-lint' (= 0.39.0) in any repository
ERROR:  Possible alternatives: scss-lint

C:\WINDOWS\system32>gem install scss-lint
Fetching: scss-lint-0.38.0.gem (100%)
WARNING: `scss-lint` has been renamed to `scss_lint` to follow proper RubyGems n
aming conventions. Update your Gemfile or relevant install scripts to install `s
css_lint`.
Successfully installed scss-lint-0.38.0
Parsing documentation for scss-lint-0.38.0
Installing ri documentation for scss-lint-0.38.0
Done installing documentation for scss-lint after 8 seconds
1 gem installed

C:\WINDOWS\system32>gem install scss_lint
scss_lint's executable "scss-lint" conflicts with scss-lint
Overwrite the executable? [yN]  y
Successfully installed scss_lint-0.39.0
Parsing documentation for scss_lint-0.39.0
Done installing documentation for scss_lint after 2 seconds
1 gem installed

As you can see I had a conflict with "scss_lint". Could this be the reason why I am getting an error?

**Comment by juanfran** [comment]
I am using gulp-scss-lint 0.2.0 with scss-lint 0.38 and node 0.12.5

If you add the verbose option you will the executed scss-lint command and see if it has any error.

**Comment by adam-l** [comment]
It started working after installing the latest versions of Node.js and Ruby. Problem solved.
