### ISSUE TITLE
Vague Error Message

### ISSUE THREAD

**Issue by scottzirkel** [juanfran/gulp-scss-lint#43]
I had misspelled the config filename, but the only error I received was

````
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Input file did not exist or was not readable
````

Would have saved me about an hour of digging had there been more details in the error message. Even the plugin name would be a good starting point for debugging.

**Comment by juanfran** [comment]
Thanks for your feedback,

I've added a better error message but I don't know why you don't have the plugin name. I throw a gulp PluginError exception with the plugin name and I get this

```
[15:59:40] Error in plugin 'gulp-scss-lint'
Message:
    Config file did not exist or was not readable
```

**Comment by scottzirkel** [comment]
That's much more helpful, thank you.

I don't know why I didn't have the plugin name either. But it was easily repeatable for me by just changing the config filename.

Thanks for the help, much appreciated!
