### ISSUE TITLE
reporterOutput only contains last file linted

### ISSUE THREAD

**Issue by ryan-perry** [juanfran/gulp-scss-lint#54]
When scanning through more than one Sass file only the last file is in the output file.

The following is the gulp task that I'm using:

gulp.task('scss-lint', function() {
 return gulp.src(['./web/scss/globals/*.scss', '!web/scss/globals/_reset.scss'])
  .pipe(scsslint({
    'config': 'scss-lint.yml',
    'reporterOutput': './lint/scss-report.json',
    'maxBuffer':  5 * 1024 * 1024,
    'endless': true,
    'sync': true
  }));
});

**Comment by juanfran** [comment]
thanks @ryan-perry but fix this with `endless: true` could be hard because the json (or xml) output should be modified when a new `scss` comes through the pipe... What do you think if `gulp-scss-lint` creates a report file for every `scss` when endless is set to `true`?

**Comment by ryan-perry** [comment]
Having a report file for each scss would be great. Awesome work on this!

**Comment by juanfran** [comment]
Hi!, in the last version you can do this

```js
gulp.task('test', function() {
  return gulp.src(['**/*.scss'])
    .pipe(scsslint({
      'endless': true,
      'endlessReporter': 'outputDir',
      'sync': true
    }));
});
```

**Comment by ryan-perry** [comment]
Awesome! Works great, thanks for the addition. I'm closing this issue since this has been resolved with the latest release.
