### ISSUE TITLE
Prevent console output

### ISSUE THREAD

**Issue by parky128** [juanfran/gulp-scss-lint#55]
Hi, I am a newbie to this tool and have got this setup and configured as I require.

However, I wondered if there was a way I could prevent any console output when the the task is being performed?

On my initial run, I encountered the maxBuffer error and so increased the size in task config options. I am now reporting the resulst to an xml file for use on a build server and so producing console output is no longer needed. 

Is there a way to do this?
Thanks

**Comment by juanfran** [comment]
Yes, with a empty custom reporter

```js
gulp.task('scss-lint', function() {
  return gulp.src('/scss/*.scss')
    .pipe(scsslint({
        customReport: function(){}
    }))
});
```
