### ISSUE TITLE
HTML Reporter

### ISSUE THREAD

**Issue by parky128** [juanfran/gulp-scss-lint#56]
Is it possible to get the results output to HTML? I can't see any options to do so from the docs.

Thanks

**Comment by juanfran** [comment]
no `gulp-scss-lint` doesn't have an html reporter because [scss-lint](https://github.com/brigade/scss-lint/) doesn't have one, sorry. Maybe you can find a way with this https://github.com/edendramis/scss-lint-html-reporter, but I don't know how.
