### ISSUE TITLE
Upgrade vinyl-fs dependency to ^2.4.0

### ISSUE THREAD

**Issue by dak** [juanfran/gulp-scss-lint#68]
vinyl-fs@^1.0.0 relies on graceful-fs versions prior to 4.0 which are incompatible with node >= 6.0:
`npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`

**Comment by juanfran** [comment]
merged your PR, thanks
