### ISSUE TITLE
Command line usage error - XML Format

### ISSUE THREAD

**Issue by JISevilla92** [juanfran/gulp-scss-lint#80]
Hi! While I was debugging an error I found that this command was failing

 "/bin/sh -c scss-lint [all the scss files] --config=scss-lint.yml --format=XML"

I executed that in the console without the bin/sh and it throwed and invalid format error

I guess something changed lately but not sure what it could be (Maybe accepted formats?)

**Comment by juanfran** [comment]
--format=XML is not longer used in scss-lint, try update gulp-scss-lint and scss-lint
