### ISSUE TITLE
No such file or directory error in macOS High Sierra

### ISSUE THREAD

**Issue by nitemarket** [juanfran/gulp-scss-lint#82]
`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby` is not available.

Please update to version 2.3

**Comment by juanfran** [comment]
`gulp-scss-lint` doesn't use Ruby directly, this plugin run a [scss-lint](https://github.com/brigade/scss-lint) command, for example `scss-lint 'test/fixtures/invalid.scss'`, try to run [scss-lint](https://github.com/brigade/scss-lint) manually to check if it works.

**Comment by juanfran** [comment]
sorry I can't help, if [scss-lint](https://github.com/brigade/scss-lint) doesn't work try to ask in that repository.

**Comment by nitemarket** [comment]
Alright. Reinstalling scss_lint helps.

`sudo gem install scss_lint`
