### ISSUE TITLE
[Error] 'scss-lint' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by pavlyukpetr** [juanfran/gulp-scss-lint#87]
Hello, I have the error when I run the lint

> Error: Command failed: scss-lint 'lik-to-my-style.scss' --config=.scss-lint.yml --format=JSON
'scss-lint' is not recognized as an internal or external command,
operable program or batch file.

Please, help me to solve it.

**Comment by juanfran** [comment]
Hi!, have you try the ruby scss-lint gem without this plugin? scss-lint must work before use it with this plugin

**Comment by pavlyukpetr** [comment]
ruby scss-lint is working itself.
Already fixed the issue.
My steps:
- reinstall the gulp-scss-lint ver 0.5.0 (before was 0.6.1)
- reinstall Ruby ver 2.4 (before had 2.5)
after updated the gulp-scss-lint to 0.6.1
It still working good.
You can close the issue.

**Comment by mgediya** [comment]
I'm using gulp and for sass compiling and still find the same issue 'scss-lint' is not recognized as an internal or external command,
operable program or batch file.

Anyone can help here ?
