### ISSUE TITLE
Depends on compromised package "event-stream"

### ISSUE THREAD

**Issue by patrickgalbraith** [juanfran/gulp-scss-lint#89]
dominictarr/event-stream#116

```
npm ls flatmap-stream
`-- gulp-scss-lint@0.7.1
  `-- event-stream@3.3.6
    `-- flatmap-stream@0.1.2
```

Recommendation at the moment is to pin the version to 3.3.4 see https://github.com/mapbox/dyno/pull/146/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 for example.

**Comment by blord-fullscreen** [comment]
Or better yet bump to ^4.0.1 and address any compatibility issues?

**Comment by patrickgalbraith** [comment]
I checked to make sure and @blord-fullscreen is right the package was removed in 4.0 so that is also an option.

See https://github.com/dominictarr/event-stream/commit/2bd63d58fe24367372690c29c7249ed1c7145601#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 for confirmation.

**Comment by AkA84** [comment]
Considering that the removal is apparently done by the same guy who [added](https://github.com/dominictarr/event-stream/commit/e3163361fed01384c986b9b4c18feb1fc42b8285) the package in the first place, can any version above 3.3.4 considered safe?

**Comment by juanfran** [comment]
thanks @patrickgalbraith, pinned to 3.3.4 in 0.7.2

**Comment by patrickgalbraith** [comment]
@juanfran Thanks!
